### ISSUE TITLE
Overridable private function warnings

### ISSUE THREAD

**Issue by jcoyne** [myfreeweb/httpotion#107]
```
warning: making private functions (process_arguments/3 in this case) overridable is deprecated
  (elixir) lib/module.ex:815: anonymous fn/2 in Module.make_overridable/2
  (stdlib) lists.erl:1338: :lists.foreach/2
  lib/httpotion.ex:355: (module)
  (elixir) src/elixir_compiler.erl:125: :elixir_compiler.dispatch_loaded/6
  (elixir) src/elixir_module.erl:191: :elixir_module.eval_form/6

warning: making private functions (prepend_protocol/1 in this case) overridable is deprecated
  (elixir) lib/module.ex:815: anonymous fn/2 in Module.make_overridable/2
  (stdlib) lists.erl:1338: :lists.foreach/2
  lib/httpotion.ex:355: (module)
  (elixir) src/elixir_compiler.erl:125: :elixir_compiler.dispatch_loaded/6
  (elixir) src/elixir_module.erl:191: :elixir_module.eval_form/6

warning: making private functions (error_to_string/1 in this case) overridable is deprecated
  (elixir) lib/module.ex:815: anonymous fn/2 in Module.make_overridable/2
  (stdlib) lists.erl:1338: :lists.foreach/2
  lib/httpotion.ex:355: (module)
  (elixir) src/elixir_compiler.erl:125: :elixir_compiler.dispatch_loaded/6
  (elixir) src/elixir_module.erl:191: :elixir_module.eval_form/6

warning: making private functions (normalize_location/2 in this case) overridable is deprecated
  (elixir) lib/module.ex:815: anonymous fn/2 in Module.make_overridable/2
  (stdlib) lists.erl:1338: :lists.foreach/2
  lib/httpotion.ex:355: (module)
  (elixir) src/elixir_compiler.erl:125: :elixir_compiler.dispatch_loaded/6
  (elixir) src/elixir_module.erl:191: :elixir_module.eval_form/6

warning: making private functions (append_query_string/2 in this case) overridable is deprecated
  (elixir) lib/module.ex:815: anonymous fn/2 in Module.make_overridable/2
  (stdlib) lists.erl:1338: :lists.foreach/2
  lib/httpotion.ex:355: (module)
  (elixir) src/elixir_compiler.erl:125: :elixir_compiler.dispatch_loaded/6
  (elixir) src/elixir_module.erl:191: :elixir_module.eval_form/6
```

**Comment by myfreeweb** [comment]
wtf elixir why :(

I guess I could just make them public…

**Comment by myfreeweb** [comment]
Haven't seen this warning in recent versions…
