### ISSUE TITLE
Getting an exception when following redirects

### ISSUE THREAD

**Issue by alex0112** [myfreeweb/httpotion#131]
Making a `GET` request on a URI that follows redirects like so:
```elixir
 payload = [
      body: "",
      follow_redirects: true,
      headers:
      [
        "...": ...,
        "Content-Type": "application/json",
      ]
    ]

HTTPotion.get "api.example.com/path/to/resource", payload
```
Produces an ArgumentException from the URI module:
```elixir
** (ArgumentError) you must merge onto an absolute URI
    (elixir) lib/uri.ex:518: URI.merge/2
    (httpotion) lib/httpotion.ex:455: HTTPotion.normalize_location/2
    (httpotion) lib/httpotion.ex:455: HTTPotion.request/3
    (project) lib/file.ex:60: File.function/1
```
Specifically this exception occurs when I send an authenticated request to the Coinbase [`accounts`](https://developers.coinbase.com/api/v2#account-resource) endpoint. 

I'm admittedly new to both Elixir and this library:  but I _suspect_ this error is being caused because HTTPotion's [`normalize_location/2`](https://github.com/myfreeweb/httpotion/blob/master/lib/httpotion.ex#L269) function calls `URI.merge/2` with the new URI from the redirect, which is constructed without prepending  `http[s]://` to the URI.  This causes the `authority` key in the URI struct to end up nil, meaning that [`URI.merge/2`](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/uri.ex#L557) is the specific version of the function being called.  I'm trying to dig into the library a bit more to find out how to print the exact URI string that's being returned from the redirect.

This hasn't happened for the other Coinbase calls ([this function](https://github.com/alex0112/aurum/blob/master/lib/request.ex#L59) for example), my suspicion is that when HTTPotion follows a redirect, the resulting string that `URI` is expected to parse is formed in a way that URI/HTTPotion doesn't expect.

If this isn't expected behavior, I'd like to submit a PR to prevent this exception from being thrown.  Otherwise, guidance is appreciated.

**Comment by myfreeweb** [comment]
> how to print the exact URI string that's being returned from the redirect

Just `IO.inspect` the arguments to `URI.merge`.

It's merging against the *current* request URI.. I'm not sure how that ended up not being absolute.
