### ISSUE TITLE
String vs binary problems, giving me errors

### ISSUE THREAD

**Issue by arthurcolle** [myfreeweb/httpotion#51]
Hi, new to Elixir but know Erlang pretty well.

I'm trying to run my application (http://github.com/arthurcolle/fxex) but when I make a simple get request it tells me:

```
** (Protocol.UndefinedError) protocol Access not implemented for %HTTPotion.Response{body: "{\n  \"disclaimer\": \"Exchange rates are provided for informational purposes only, and do not constitute financial advice of any kind. Although every attempt is made to ensure quality, NO guarantees are given whatsoever of accuracy, validity, availability, or fitness for any purpose - please use at your own risk. All usage is subject to your acceptance of the Terms and Conditions of Service, available at: https://openexchangerates.org/terms/\",\n  \"license\": \"Data sourced from various providers with public-facing APIs; copyright may apply; resale is prohibited; no warranties given of any kind. Bitcoin data provided by http://coindesk.com. All usage is subject to your acceptance of the License Agreement available at: https://openexchangerates.org/license/\",\n  \"timestamp\": 1429855262,\n  \"base\": \"USD\",\n  \"rates\": {\n    \"AED\": 3.673121,\n    \"AFN\": 57.8736,\n    \"ALL\": 129.7089,\n    \"AMD\": 473.443998,\n    \"ANG\": 1.78902,\n    \"AOA\": 109.0425,\n    \"ARS\": 8.89224,\n    \"AUD\": 1.285626,\n    \"AWG\": 1.7925,\n    \"AZN\": 1.051675,\n    \"BAM\": 1.812719,\n    \"BBD\": 2,\n    \"BDT\": 77.5487,\n    \"BGN\": 1.811379,\n    \"BHD\": 0.37704,\n    \"BIF\": 1560.663333,\n    \"BMD\": 1,\n    \"BND\": 1.341802,\n    \"BOB\": 6.885179,\n    \"BRL\": 2.978822,\n    \"BSD\": 1,\n    \"BTC\": 0.004319313,\n    \"BTN\": 63.3652,\n    \"BWP\": 9.937702,\n    \"BYR\": 14393.133333,\n    \"BZD\": 1.990659,\n    \"CAD\": 1.216211,\n    \"CDF\": 930.8,\n    \"CHF\": 0.957962,\n    \"CLF\": 0.024598,\n    \"CLP\": 615.879204,\n    \"CNY\": 6.178422,\n    \"COP\": 2470.311667,\n    \"CRC\": 529.702275,\n    \"CUC\": 1,\n    \"CUP\": 0.998363,\n    \"CVE\": 102.207375,\n    \"CZK\": 25.39055,\n    \"DJF\": 177.632001,\n    \"DKK\": 6.910133,\n    \"DOP\": 44.65573,\n    \"DZD\": 98.2845,\n    \"EEK\": 14.51835,\n    \"EGP\": 7.617534,\n    \"ERN\": 15.1151,\n    \"ETB\": 20.44761,\n    \"EUR\": 0.925127,\n    \"FJD\": 2.03751,\n    \"FKP\": 0.664372,\n    \"GBP\": 0.664372,\n    \"GEL\": 2.2624,\n    \"GGP\": 0.664372,\n    \"GHS\": 3.836624,\n    \"GIP\": 0.664372,\n    \"GMD\": 43.00158,\n    \"GNF\": 7234.4,\n    \"GTQ\": 7.727193,\n    \"GYD\": 206.305752,\n    \"HKD\": 7.749997,\n    \"HNL\": 21.47521,\n    \"HRK\": 7.025943,\n    \"HTG\": 47.27169,\n    \"HUF\": 278.167998,\n    \"IDR\": 12936.916667,\n    \"ILS\": 3.928771,\n    \"IMP\": 0.664372,\n    \"INR\": 63.37642,\n    \"IQD\": 1182.059217,\n    \"IRR\": 28203.666667,\n    \"ISK\": 135.959,\n    \"JEP\": 0.664372,\n    \"JMD\": 114.912801,\n    \"JOD\": 0.70833,\n    \"JPY\": 119.575699,\n    \"KES\": 94.024179,\n    \"KGS\": 61.710667,\n    \"KHR\": 3999.585016,\n    \"KMF\": 456.328781,\n    \"KPW\": 900.09,\n    \"KRW\": 1080.218315,\n    \"KWD\": 0.302314,\n    \"KYD\": 0.823171,\n    \"KZT\": 185.6891,\n    \"LAK\": 8092.595,\n    \"LBP\": 1507.888333,\n    \"LKR\": 132.6568,\n    \"LRD\": 84.553335,\n    \"LSL\": 12.17813,\n    \"LTL\": 2.933867,\n    \"LVL\": 0.651597,\n    \"LYD\": 1.363291,\n    \"MAD\": 9.926872,\n    \"MDL\": 18.47916,\n    \"MGA\": 3080.914967,\n    \"MKD\": 57.03369,\n    \"MMK\": 1076.449988,\n    \"MNT\": 1963.166667,\n    \"MOP\": 7.975066,\n    \"MRO\": 314.022833,\n    \"MTL\": 0.397267,\n    \"MUR\": 35.9687,\n    \"MVR\": 15.256538,\n    \"MWK\": 440.478202,\n    \"MXN\": 15.36043,\n    \"MYR\": 3.5993,\n    \"MZN\": 35.233333,\n    \"NAD\": 12.17823,\n    \"NGN\": 198.771401,\n    \"NIO\": 26.7191,\n    \"NOK\": 7.853823,\n    \"NPR\": 100.92236,\n    \"NZD\": 1.322367,\n    \"OMR\": 0.384969,\n    \"PAB\": 1,\n    \"PEN\": 3.13101,\n    \"PGK\": 2.686497,\n    \"PHP\": 44.22541,\n    \"PKR\": 101.4992,\n    \"PLN\": 3.70452,\n    \"PYG\": 5009.971719,\n    \"QAR\": 3.640189,\n    \"RON\": 4.092864,\n    \"RSD\": 111.8845,\n    \"RUB\": 50.83582,\n    \"RWF\": 688.7738,\n    \"SAR\": 3.749258,\n    \"SBD\": 7.743432,\n    \"SCR\": 13.47469,\n    \"SDG\": 5.953994,\n    \"SEK\": 8.65835,\n    \"SGD\": 1.341455,\n    \"SHP\": 0.664372,\n    \"SLL\": 4363.333333,\n    \"SOS\": 703.255102,\n    \"SRD\": 3.3302,\n    \"STD\": 22712.35,\n    \"SVC\": 8.734096,\n    \"SYP\": 214.72235,\n    \"SZL\": 12.18003,\n    \"THB\": 32.4593,\n    \"TJS\": 6.1587,\n    \"TMT\": 3.500067,\n    \"TND\": 1.951288,\n    \"TOP\": 2.025876,\n    \"TRY\": 2.707308,\n    \"TTD\": 6.33743,\n    \"TWD\": 31.01267,\n    \"TZS\": 1930.46,\n    \"UAH\": 22.43285,\n    \"UGX\": 2997.001667,\n    \"USD\": 1,\n    \"UYU\": 26.66482,\n    \"UZS\": 2506.599967,\n    \"VEF\": 6.318541,\n    \"VND\": 21586.666667,\n    \"VUV\": 105.771666,\n    \"WST\": 2.472739,\n    \"XAF\": 608.548875,\n    \"XAG\": 0.06319767,\n    \"XAU\": 0.00083894,\n    \"XCD\": 2.70102,\n    \"XDR\": 0.722785,\n    \"XOF\": 607.904115,\n    \"XPF\": 110.66831,\n    \"YER\": 214.9484,\n    \"ZAR\": 12.16738,\n    \"ZMK\": 5253.075255,\n    \"ZMW\": 7.359064,\n    \"ZWL\": 322.355006\n  }\n}", headers: ["Access-Control-Allow-Origin": "*", "Cache-Control": "public", Connection: "close", "Content-Length": "4402", "Content-Type": "application/json; charset=utf-8", Date: "Fri, 24 Apr 2015 06:12:04 GMT", ETag: "\"16e6e8b1c39237051c16c0d7fb174da3\"", "Last-Modified": "Fri, 24 Apr 2015 06:01:02 GMT", Server: "Apache"], status_code: 200}
    (elixir) lib/access.ex:1: Access.impl_for!/1
    (elixir) lib/access.ex:47: Access.get/2
      (fxex) lib/fxex.ex:23: Fxex.work/0
iex(1)>

```

Was wondering if you had any pointers?

Thanks

**Comment by myfreeweb** [comment]
Have you tried to read the error message? ;-)

The [Access protocol](http://elixir-lang.org/docs/master/elixir/Access.html) is not implemented for `HTTPotion.Response`. Because it's [a struct](http://elixir-lang.org/getting-started/structs.html):

> Notice that we referred to structs as bare maps because none of the protocols implemented for maps are available for structs. For example, you can't enumerate nor access a struct

You're probably doing `response[:body]` for some reason. Don't do this! It should simply be `response.body`.

I'll make it more clear in the README.

**Comment by arthurcolle** [comment]
Thanks for the response! I actually managed to get it working using httpc/inets, still grappling with some of the syntactic differences. https://github.com/arthurcolle/fxex if you're curious. :)
